### ISSUE TITLE
Point homepage at http://stack.formidable.com/chai-jq/

### ISSUE THREAD

**Issue by david-davidson** [FormidableLabs/chai-jq#23]
Hi @ryan-roemer,

Now that our GitHub Pages sites live at stack.formidable.com, the official URL here is http://stack.formidable.com/chai-jq/ (the old URL redirects there just fine).

Looks like I don't have write/edit access here--when you have a sec, mind updating the homepage field at the top of the repo? Thanks!

**Comment by ryan-roemer** [comment]
Done :)
