### ISSUE TITLE
TypeError: expect(...).to.have.$prop is not a function

### ISSUE THREAD

**Issue by syedimranbasha** [FormidableLabs/chai-jq#24]
**I am using below code**
it('should work', function() {
    expect($("<input type=\"checkbox\" checked=\"checked\" />")).to.have.$prop("checked", true);
});

When I run the above code in Karma I am receiving the below error

**TypeError: expect(...).to.have.$prop is not a function**

**Note:**
1. All chai.Assertion.addMethod() in chai-jq are getting executed. I have verified this in debug mode. But still $prop is not recognized.
1. I am using jquery-1.8.3.js

**Comment by ryan-roemer** [comment]
@syedimranbasha -- Can you get me a repo or gist with full steps to a reproduction of the issue you're seeing?

**Comment by syedimranbasha** [comment]
**test.js**
define([], function() {
	describe('Instantiation', function() {
		it('should create div element with id "QuickBooks_24"', function() {
			//expect($(this.view.el).find('QuickBooks_24').html()).to.have.$prop('id', 'QuickBooks_24');
			expect($("<input type=\"checkbox\" checked=\"checked\" />")).to.have.$prop("checked", true);
		});
	});

});

Sequence if script tags in he generated karma debug.html file
  
  <script type="text/javascript" src="/base/node_modules/karma-jquery/jquery/jquery-1.8.3.js"></script>
<script type="text/javascript" src="/base/node_modules/sinon/pkg/sinon.js"></script>
<script type="text/javascript" src="/base/node_modules/chai/chai.js"></script>
<script type="text/javascript" src="/base/node_modules/sinon-chai/lib/sinon-chai.js"></script>
<script type="text/javascript" src="/base/node_modules/karma-chai-sinon/adapter.js"></script>
<script type="text/javascript" src="/base/node_modules/chai-jquery/chai-jquery.js"></script>
<script type="text/javascript" src="/base/node_modules/requirejs/require.js"></script>
<script type="text/javascript" src="/base/node_modules/karma-requirejs/lib/adapter.js"></script>
<script type="text/javascript" src="/base/node_modules/mocha/mocha.js"></script>
<script type="text/javascript" src="/base/node_modules/karma-mocha/lib/adapter.js"></script>
  <script type="text/javascript">
    window.__karma__.loaded();
  </script>

**Comment by ryan-roemer** [comment]
Can I get a full reproduction? Something I can download and try on my computer. It's very likely the config/chai/chai-jq setup is the issue, not this assert

**Comment by syedimranbasha** [comment]
I am facing the issue in my actual production code hence I am providing spec file and karma.conf file. Please let me know if you need any other file to investigate the issue further.

[
[karma.conf.js.txt](https://github.com/FormidableLabs/chai-jq/files/378723/karma.conf.js.txt)
[spec.js.txt](https://github.com/FormidableLabs/chai-jq/files/378724/spec.js.txt)

](url)

**Comment by syedimranbasha** [comment]
I agree with you that there might not be any issue with the Assert. 
Apart form including chai.js and chai-jq.js file, Is there any chai-jq setup ?

**Comment by ryan-roemer** [comment]
You're using AMD and should follow the AMD section of this guide: https://github.com/FormidableLabs/chai-jq#integration

Basically, in a global setup script (block in HTML page or separate JS file that's globally included) you need to include both `chai` and `chai-jq` and do:

```js
chai.use(chaiJq);
```

E.g., could look like:

```js
require(["chai", "chai-jq"], function (chai, plugin) {
  // Inject plugin.
  chai.use(plugin);

  // Rest of your test code here...
});
```

Also side note -- you're _also_ including the `chai-jquery` framework in Karma which is basically an alternate set of the same asserts, so you probably don't want both this and that plugin...

Best case for me to help, give me something completely downloadable -- multiple files in a gist or a full repo and installation steps (e.g., `npm install`, then `karma <flags`, etc.). Otherwise, I'm just guessing as to how your whole setup comes together...

**Comment by syedimranbasha** [comment]
**Please use the below zip**
[
[karma-issue.zip.txt](https://github.com/FormidableLabs/chai-jq/files/380148/karma-issue.zip.txt)
](url)

**Steps to reproduce**
1. Rename karma-issue.zip.txt to karma-issue.zip
2. Run npm install at root folder (where package.json exists)
3.. Run "karma start"

**I get the below error**
TypeError: expect(...).to.have.$prop is not a function

**Comment by ryan-roemer** [comment]
@syedimranbasha -- Thanks for the zip file. On reviewing this, the underlying thing is that you are at the very beginning of your test infrastructure journey and likely need to read a lot more online / get a good book to help kickstart your testing learning.

There are a lot of things that need to be changed up to just get your infrastructure even running here. And most significantly, you're example uses `chai-jquery`, which is **not** this library -- this is `chai-jq`, an alternate plugin for the same thing.

To help you keep going to the next step, I've actually gone through and wired up something that will work. Here's the diff:

```diff
diff --git a/js/test/test-main.js b/js/test/test-main.js
index c2e35c7..3a1584b 100755
--- a/js/test/test-main.js
+++ b/js/test/test-main.js
@@ -10,5 +10,23 @@ for (var file in window.__karma__.files) {
 require.config({
 	baseUrl: "/base/js/src",
 	deps: tests,
-	callback: window.__karma__.start
-});
\ No newline at end of file
+
+	// You have an incorrect path to chai and chai-jq since your baseUrl
+	// is /js/src. Add aliases here.
+	paths: {
+		"chai": "/base/node_modules/chai/chai",
+		"chai-jq": "/base/node_modules/chai-jq/chai-jq",
+		"jquery": "/base/node_modules/jquery/dist/jquery"
+	}
+});
+
+// You need to add the chai plugin _before_ karma starts.
+require(["chai", "chai-jq"], function (chai, chaiJq) {
+	// Export chai expect to a global.
+	window.expect = chai.expect;
+
+	// Hook in plugin.
+	chai.use(chaiJq);
+
+	window.__karma__.start();
+});
diff --git a/karma.conf.js b/karma.conf.js
index e07ae77..7c51cdc 100755
--- a/karma.conf.js
+++ b/karma.conf.js
@@ -8,27 +8,34 @@ module.exports = function(config) {
     basePath: '',
 
     // frameworks to use
-    frameworks: ['mocha', 'requirejs', 'chai-jquery', 'chai-sinon', 'jquery-1.8.3'],
+    // You're not using `'chai-jquery',`, you're using `chai-jq`.
+    // Also, I'm not sure all of these are real frameworks...
+    frameworks: ['mocha', 'requirejs'],
 
     // list of files / patterns to load in the browser
     files: [
 	// { pattern: 'tests/lib/chai.js', watched: false },
 
-      {pattern: 'js/lib/*.js', included: false},
-	
-	  { pattern:'js/src/**/*.js', included:false},
+      // Need to actually serve node modules.
+      {pattern: 'node_modules/chai/*.js', included: false},
+      {pattern: 'node_modules/chai-jq/*.js', included: false},
+      {pattern: 'node_modules/jquery/dist/*.js', included: false},
+
+   //    {pattern: 'js/lib/*.js', included: false},
+
+	  // { pattern:'js/src/**/*.js', included:false},
 
       {pattern: 'js/test/**/*.js', included: false},
 
-      {pattern: 'template/*.html', included: false},
+   //    {pattern: 'template/*.html', included: false},
 
-      'js/test/test-main.js',
+      'js/test/test-main.js'
     ],
 
 
     // list of files to exclude
     exclude: ['js/src/main.js', 'js/lib/require.js'],
-    
+
      // web server port
     port: 9876,
 
@@ -41,7 +48,11 @@ module.exports = function(config) {
     // possible values: config.LOG_DISABLE || config.LOG_ERROR ||
 	// config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
     logLevel: config.LOG_INFO,
-	
+
+    client: {
+        captureConsole: true
+    },
+
     // enable / disable watching file and executing tests whenever any file
 	// changes
     autoWatch: true,
diff --git a/package.json b/package.json
old mode 100755
new mode 100644
index 194ad51..c2d1576
--- a/package.json
+++ b/package.json
@@ -10,6 +10,7 @@
   "license": "ISC",
   "devDependencies": {
     "chai": "^3.5.0",
+    "chai-jq": "0.0.9",
     "chai-jquery": "^2.0.0",
     "grunt": "^1.0.1",
     "grunt-contrib-jshint": "^1.0.0",
```

**Comment by syedimranbasha** [comment]
Ryan,

Thanks for your inputs. With few modifications to your code it worked for me.

**Want to mention few things based on my investigation**
1. I cant completely eliminate dependency on lib folder form karma.conf.js as node_modules are only for unit test framework karma to work. My actual code uses libraries directly from lib/CDN location.  So I need to retain lib folder pattern it in karma.conf.js

2. There are 2 ways to integrate 'chai-jq in the test code. #1 -Use Karma plugin and #2 - Directly require('chai-jq') the library. I thought I can find solution for #1.  But looks like karma plugin doesn't work out of the box. After spending quite a bit amount of time I decided not to use karma plugin for 'chai-jq' rather use the requirejs modules directly in 'test-main.js'. So in my case second option as you suggested has worked for me.

3. My actual project is backbone based and I was trying to test backbonejs models, collections, routers and views. I got around 100+ unit test cases written and integreated with CI/CD systems but got stuck at unit testing views. But in the interest of not polluting the details of all other aspects of testing, I just provided the basic files by trimming most of the irrelevant content. So karma.conf.js I have provide is the trimmed version of the actual one.

4. Here are the libraries I am using for my Unit testing after exploring multiple options.

Backbone + RequireJS+ Mocha + Karma + SinonJS + Chai + Chai-JQ + Grunt

I have read many books but they just limit to covering html based test execution which is the simplest of all. I didn't found a book which covers integration of all the above frameworks. But after researching found few independent articles and after stitching them together I got my Unit Test working.  If you have come across any such book, please let me know.

**Thanks for your time for helping me around.**

**Comment by ryan-roemer** [comment]
Ah makes sense. Glad to hear you're going in a working direction!
